image: maven:3.6.3-openjdk-17

stages:
  - compile
  - unit_tests
  - gui_tests
  - checkstyle
  - sonarcloud

variables:
  SONAR_USER_HOME: "$CI_PROJECT_DIR/.sonar"
  GIT_DEPTH: "0"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .sonar/cache

compile:
  stage: compile
  script:
    - $MAVEN_HOME/bin/mvn clean compile

unit_tests:
  stage: unit_tests
  script:
    - mvn clean compile
    - mvn test -Dgroups=unit

  artifacts:
    paths:
      - target/surefire-reports
      - target/failsafe-reports
      - target/site/jacoco/jacoco.xml
    expire_in: 1 hour
    reports:
      junit:
        - target/surefire-reports/*.xml
        - target/failsafe-reports/*.xml

gui_tests:
  stage: gui_tests
  image: maven:3.6.3-openjdk-17
  when: on_success
  before_script:
    - apt-get update && apt-get install -y xvfb
  script:
    - mvn clean compile
    - Xvfb :99 -screen 0 1024x768x24 &
    - export DISPLAY=:99
    - mvn test -Dgroups=gui -Djava.awt.headless=false
  artifacts:
    when: always
    paths:
      - target/surefire-reports
      - target/failsafe-reports
      - target/site/jacoco/jacoco.xml
      - target/screenshots/
    expire_in: 1 hour
    reports:
      junit:
        - target/surefire-reports/*.xml
        - target/failsafe-reports/*.xml

# checkstyle:
#   stage: checkstyle
#   script:
#     - mvn checkstyle:check
#   only:
#     - main
#     - merge_requests

#sonarcloud-check:
# stage: sonarcloud
# needs:
#   - job: unit_tests
#      artifacts: true
#    - job: gui_tests
#      artifacts: true
#  script:
#    - $MAVEN_HOME/bin/mvn -DskipTests -Djava.awt.headless=true -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml verify sonar:sonar -Dsonar.projectKey=tafel_software-hs-osnabrueck_Tafel_Projekt -Dsonar.organization=tafel-software-hs-osnabrueck -Dsonar.host.url="$SONAR_HOST_URL" -Dsonar.login="$SONAR_TOKEN"
#  only:
#    - main
#    - merge_requests
