sonar.projectKey=tafel_software-hs-osnabrueck_Tafel_Projekt
sonar.organization=Tafel_Software-Hs-Osnabrueck

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=tafel_2024
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file
sonar.sources=src/main

# Path to the tests directory
sonar.tests=src/test/java

# Coverage report paths
sonar.jacoco.reportPaths=target/jacoco.exec
sonar.java.coveragePlugin=jacoco
sonar.jacoco.reportPaths=target/site/jacoco/jacoco.xml

# Encoding of the source code
sonar.sourceEncoding=UTF-8
