#MySQL database information
#Fri Sep 28 15:04:20 CEST 2018
jdbc.username=lingener-tafel
jdbc.dbName=lingener-tafel
jdbc.port=3306
jdbc.hostname=fensalir.lin.hs-osnabrueck.de
jdbc.password=
db.lastbackup=28.09.2018
